import type { JournalTemplateId, SurveyPaper } from "./types";

export type TemplateMeta = {
  id: JournalTemplateId;
  name: string;
  venueHint: string;
  description: string;
  citationStyle: "numbered" | "author-year";
  columns: 1 | 2;
  className: string;
};

export const TEMPLATES: TemplateMeta[] = [
  {
    id: "ieee",
    name: "IEEE Transactions",
    venueHint: "IEEE Trans. / IEEE Access style",
    description: "Two-column numbered citations, compact abstract, keywords line.",
    citationStyle: "numbered",
    columns: 2,
    className: "tpl-ieee",
  },
  {
    id: "acm",
    name: "ACM",
    venueHint: "ACM Computing Surveys style",
    description: "CCS-like keywords, numbered refs, survey-friendly headings.",
    citationStyle: "numbered",
    columns: 1,
    className: "tpl-acm",
  },
  {
    id: "springer",
    name: "Springer",
    venueHint: "Springer journal article style",
    description: "Single column with numbered headings and reference list.",
    citationStyle: "numbered",
    columns: 1,
    className: "tpl-springer",
  },
  {
    id: "elsevier",
    name: "Elsevier",
    venueHint: "Elsevier / ScienceDirect style",
    description: "Structured abstract feel, author-year friendly numbering retained for draft.",
    citationStyle: "numbered",
    columns: 1,
    className: "tpl-elsevier",
  },
  {
    id: "nature",
    name: "Nature-style",
    venueHint: "Nature portfolio concise style",
    description: "Shorter abstract emphasis and cleaner section rhythm.",
    citationStyle: "numbered",
    columns: 1,
    className: "tpl-nature",
  },
];

export function getTemplate(id: JournalTemplateId): TemplateMeta {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
}

function sectionNumber(index: number, template: JournalTemplateId): string {
  if (template === "ieee") {
    const romans = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"];
    return romans[index] ?? String(index + 1);
  }
  return String(index + 1);
}

export function paperToMarkdown(paper: SurveyPaper): string {
  const tpl = getTemplate(paper.template);
  const lines: string[] = [];
  lines.push(`# ${paper.title}`);
  lines.push("");
  lines.push(`**Authors:** ${paper.authorsPlaceholder}`);
  lines.push(`**Template:** ${tpl.name}`);
  lines.push("");
  lines.push("## Abstract");
  lines.push(paper.abstract);
  lines.push("");
  lines.push(`**Keywords:** ${paper.keywords.join("; ")}`);
  lines.push("");

  let major = 0;
  for (const section of paper.sections) {
    if (section.level === 1) {
      const num = sectionNumber(major, paper.template);
      major++;
      lines.push(`## ${num}. ${section.heading.toUpperCase()}`);
    } else {
      lines.push(`### ${section.heading}`);
    }
    lines.push("");
    lines.push(section.content);
    lines.push("");
  }

  if (paper.figures.length) {
    lines.push("## Figures");
    lines.push("");
    for (const fig of paper.figures) {
      lines.push(`### ${fig.title}`);
      lines.push("");
      lines.push(fig.caption);
      lines.push("");
      lines.push("```svg");
      lines.push(fig.svg);
      lines.push("```");
      lines.push("");
    }
  }

  lines.push("## References");
  lines.push("");
  for (const ref of paper.references) {
    lines.push(ref.text);
  }
  lines.push("");
  lines.push("---");
  lines.push(
    `_Draft generated by SurveyForge on ${paper.metadata.generatedAt}. Humanized: ${paper.metadata.humanized}. Validate all citations against primary sources before submission._`
  );
  return lines.join("\n");
}

export function paperToLatex(paper: SurveyPaper): string {
  const isIeee = paper.template === "ieee";
  const preamble = isIeee
    ? `\\documentclass[conference]{IEEEtran}
\\usepackage{graphicx}
\\usepackage{cite}
\\begin{document}
\\title{${escapeLatex(paper.title)}}
\\author{${escapeLatex(paper.authorsPlaceholder)}}
\\maketitle
\\begin{abstract}
${escapeLatex(paper.abstract)}
\\end{abstract}
\\begin{IEEEkeywords}
${escapeLatex(paper.keywords.join(", "))}
\\end{IEEEkeywords}`
    : `\\documentclass[11pt]{article}
\\usepackage{graphicx}
\\usepackage[margin=1in]{geometry}
\\begin{document}
\\title{${escapeLatex(paper.title)}}
\\author{${escapeLatex(paper.authorsPlaceholder)}}
\\maketitle
\\begin{abstract}
${escapeLatex(paper.abstract)}
\\end{abstract}
\\noindent\\textbf{Keywords:} ${escapeLatex(paper.keywords.join("; "))}`;

  const body = paper.sections
    .map((section) => {
      const cmd = section.level === 1 ? "section" : "subsection";
      return `\\${cmd}{${escapeLatex(section.heading)}}\n${escapeLatex(section.content)}\n`;
    })
    .join("\n");

  const figs = paper.figures
    .map(
      (fig) =>
        `\\begin{figure}[ht]\\centering\\fbox{\\parbox{0.9\\linewidth}{\\textit{[SVG figure: ${escapeLatex(fig.title)}]}}}\\caption{${escapeLatex(fig.caption)}}\\label{fig:${fig.id}}\\end{figure}`
    )
    .join("\n\n");

  const refs = paper.references
    .map((r) => `\\bibitem{${r.key}} ${escapeLatex(r.text.replace(/^\[\d+\]\s*/, ""))}`)
    .join("\n");

  return `${preamble}

${body}

${figs}

\\begin{thebibliography}{99}
${refs}
\\end{thebibliography}
\\end{document}
`;
}

function escapeLatex(s: string): string {
  return s
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

export function paperToHtml(paper: SurveyPaper): string {
  const tpl = getTemplate(paper.template);
  let major = 0;
  const sectionsHtml = paper.sections
    .map((section) => {
      if (section.level === 1) {
        const num = sectionNumber(major, paper.template);
        major++;
        return `<section class="section"><h2>${num}. ${escapeHtml(section.heading)}</h2>${section.content
          .split(/\n{2,}/)
          .map((p) => `<p>${escapeHtml(p)}</p>`)
          .join("")}</section>`;
      }
      return `<section class="subsection"><h3>${escapeHtml(section.heading)}</h3>${section.content
        .split(/\n{2,}/)
        .map((p) => `<p>${escapeHtml(p)}</p>`)
        .join("")}</section>`;
    })
    .join("\n");

  const figuresHtml = paper.figures
    .map(
      (fig, idx) =>
        `<figure class="paper-figure" id="${fig.id}">
          ${fig.svg}
          <figcaption><strong>Fig. ${idx + 1}.</strong> ${escapeHtml(fig.caption)}</figcaption>
        </figure>`
    )
    .join("\n");

  const refsHtml = paper.references.map((r) => `<li id="${r.id}">${escapeHtml(r.text.replace(/^\[\d+\]\s*/, ""))}</li>`).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${escapeHtml(paper.title)}</title>
<style>
  :root { --ink:#0c1f2e; --sea:#1a6b7a; --muted:#5a6b75; }
  body { font-family: "Times New Roman", Times, serif; color: var(--ink); margin: 0; background: #fff; }
  .page { max-width: ${tpl.columns === 2 ? "920px" : "780px"}; margin: 0 auto; padding: 48px 32px 80px; }
  .tpl-ieee .columns { column-count: 2; column-gap: 28px; }
  .tpl-ieee .front { column-span: all; }
  h1 { font-size: 22px; text-align: center; line-height: 1.25; margin-bottom: 8px; }
  .authors { text-align: center; font-size: 13px; margin-bottom: 20px; color: var(--muted); }
  .abstract { font-size: 12.5px; margin-bottom: 12px; }
  .abstract strong { display: block; text-align: center; margin-bottom: 6px; }
  .keywords { font-size: 12px; margin-bottom: 22px; }
  h2 { font-size: 13px; text-transform: ${paper.template === "ieee" ? "uppercase" : "none"}; margin: 18px 0 8px; }
  h3 { font-size: 12.5px; margin: 14px 0 6px; font-style: italic; }
  p { font-size: 12.5px; line-height: 1.45; text-align: justify; margin: 0 0 8px; }
  .paper-figure { margin: 16px 0; break-inside: avoid; }
  .paper-figure svg { max-width: 100%; height: auto; display: block; margin: 0 auto; }
  figcaption { font-size: 11px; margin-top: 6px; text-align: center; }
  ol.refs { padding-left: 18px; font-size: 11.5px; }
  ol.refs li { margin-bottom: 6px; }
  .meta { margin-top: 28px; font-size: 10px; color: var(--muted); border-top: 1px solid #d5dee3; padding-top: 10px; }
  .tpl-nature h1 { font-family: Georgia, serif; font-size: 26px; }
  .tpl-acm h1 { font-family: "Helvetica Neue", Arial, sans-serif; font-size: 24px; letter-spacing: -0.02em; }
  .tpl-elsevier .abstract { border-left: 3px solid var(--sea); padding-left: 12px; }
  .tpl-springer h2 { color: var(--sea); text-transform: none; font-size: 15px; }
</style>
</head>
<body>
  <article class="page ${tpl.className}">
    <header class="front">
      <h1>${escapeHtml(paper.title)}</h1>
      <div class="authors">${escapeHtml(paper.authorsPlaceholder)} · ${escapeHtml(tpl.venueHint)}</div>
      <div class="abstract"><strong>Abstract</strong><p>${escapeHtml(paper.abstract)}</p></div>
      <div class="keywords"><strong>Keywords—</strong>${escapeHtml(paper.keywords.join("; "))}</div>
    </header>
    <div class="${tpl.columns === 2 ? "columns" : "single"}">
      ${sectionsHtml}
      ${figuresHtml}
      <section>
        <h2>${paper.template === "ieee" ? "References" : "References"}</h2>
        <ol class="refs">${refsHtml}</ol>
      </section>
    </div>
    <p class="meta">SurveyForge draft · matrix ${paper.metadata.matrixPaperCount} · discovered ${paper.metadata.discoveredPaperCount} · humanized ${paper.metadata.humanized ? "yes" : "no"} · ${escapeHtml(paper.metadata.generatedAt)}. Validate citations before submission.</p>
  </article>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
